# Generated by Django 3.2.13 on 2022-05-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naver_id', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('publish_date', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('aladin_url', models.CharField(max_length=500)),
                ('kyobo_url', models.CharField(max_length=500)),
                ('yes24_url', models.CharField(max_length=500)),
                ('interpark_url', models.CharField(max_length=500)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.subcategory')),
            ],
        ),
    ]
