# Generated by Django 3.2.13 on 2022-05-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(max_length=200),
        ),
    ]
