# Generated by Django 3.2.13 on 2022-06-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220520_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_review',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
