# Generated by Django 3.2.13 on 2022-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_total_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_review',
            field=models.CharField(max_length=100),
        ),
    ]
