# Generated by Django 3.2.13 on 2022-06-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_total_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compare_book_naver_id', models.CharField(max_length=300)),
                ('score', models.FloatField()),
                ('target_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
