# Generated by Django 3.2.13 on 2022-06-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_bestseller_platformanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformanalysis',
            name='value',
        ),
    ]
