# Generated by Django 3.2.13 on 2022-06-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20220603_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='sub_category',
        ),
    ]
