# Generated by Django 3.2.13 on 2022-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
